language: r
sudo: required
cache: packages
services:
  - docker
r_packages:
  - covr
before_script:
  - docker pull bfirsh/reticulate-splines
env:
  - RETICULATE_PYTHON=$(which python3)
after_install:
  - Rscript -e 'reticulate::py_config()'
after_success:
  - Rscript -e 'covr::codecov()'
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - python3-pip
      - python3-numpy
      - python3-requests
