# DO NOT CHANGE the "init" and "install" sections below

image: Visual Studio 2017

environment:
  NOT_CRAN: true
  USE_RTOOLS: true
  PYTHON: "C:\\Python35"
  RETICULATE_PYTHON: "C:\\Python35"

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - docker pull bfirsh/reticulate-splines
  - "%PYTHON%\\python.exe -m pip install setuptools numpy pypiwin32 requests"
  - travis-tool.sh install_deps

before_test:
  - echo %RETICULATE_PYTHON%
  - echo %PATH%
  - R -q -e "reticulate::py_discover_config('requests')"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
